---
- name: Systemd | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ argon_node_user }}"
    group: "{{ argon_node_user }}"
  loop:
    - "{{ _argon_node_chainspec_file | dirname }}"
    - "{{ _argon_node_wasm_runtime_base_path }}"
    - "{{ _argon_node_p2p_key_file | dirname }}"
  register: _argon_node_create_directories_register

- name: Chain | Copy {{ argon_node_app_name }} chainspec files
  ansible.builtin.template:
    src: "{{ argon_node_chainspec }}"
    owner: "{{ argon_node_user }}"
    group: "{{ argon_node_user }}"
    dest: "{{ _argon_node_chainspec_file }}"
    mode: "0600"
  notify: Restart service argon node
  ignore_errors: "{{ _argon_node_create_directories_register.changed }}"
  when: argon_node_chainspec != '' and not argon_node_chainspec.startswith('http')

- name: Chain | Download {{ argon_node_app_name }} chainspec files
  ansible.builtin.get_url:
    url: "{{ argon_node_chainspec }}"
    owner: "{{ argon_node_user }}"
    group: "{{ argon_node_user }}"
    dest: "{{ _argon_node_chainspec_file }}"
    mode: "0600"
    force: true
  notify: Restart service argon node
  when:
    - argon_node_chainspec != ''
    - argon_node_chainspec.startswith('http')
    - not ansible_check_mode # (Bug ansible/ansible#65687)

- name: Chain | Copy {{ argon_node_app_name }} p2p key file
  ansible.builtin.copy:
    content: "{{ argon_node_p2p_private_key }}"
    owner: "{{ argon_node_user }}"
    group: "{{ argon_node_user }}"
    dest: "{{ _argon_node_p2p_key_file }}"
    mode: "0600"
  notify: Restart service argon node
  ignore_errors: "{{ _argon_node_create_directories_register.changed }}"
  when: argon_node_p2p_private_key != ''
