---
# Ntp server to use for date synchronization
# Default is worldwide pool
ntp_servers:
  - 0.pool.ntp.org iburst
  - 1.pool.ntp.org iburst
  - 2.pool.ntp.org iburst
  - 3.pool.ntp.org iburst

# Restrict access on ntp server
# Default is: ::1, 127.0.0.1
ntp_restrict:
  - default nomodify notrap nopeer noquery
  - 127.0.0.1
  - ::1

# Leap seconds definition provided by tzdata
ntp_leap: true
ntp_leapfile: /usr/share/zoneinfo/leap-seconds.list

ntp_driftfile: /var/lib/ntp/drift
