---
- name: Copy journald config
  ansible.builtin.copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: "0644"

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true
    enabled: true
  changed_when: false

- name: Ensure syslog rotation has size limit
  ansible.builtin.copy:
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: "0644"
    content: |
      /var/log/syslog
      /var/log/mail.info
      /var/log/mail.warn
      /var/log/mail.err
      /var/log/mail.log
      /var/log/daemon.log
      /var/log/kern.log
      /var/log/auth.log
      /var/log/user.log
      /var/log/lpr.log
      /var/log/cron.log
      /var/log/debug
      /var/log/messages
      {
          su root syslog
          rotate 4
          daily
          size 100M
          missingok
          notifempty
          compress
          delaycompress
          sharedscripts
          postrotate
              /usr/lib/rsyslog/rsyslog-rotate
          endscript
      }
