---
- name: Get command output
  ansible.builtin.shell: |
    set -o pipefail
    journalctl -u argon --no-pager > /root/argon.log
    tail -n 10000 /root/argon.log
  become: true
  args:
    executable: /bin/bash
  changed_when: false
  register: command_output

- name: Result
  ansible.builtin.debug:
    msg: "Command result: {{ command_output.stdout }}"

- name: Remove log
  ansible.builtin.file:
    path: /root/argon.log
    state: absent
