---
all:
  vars:
    binary_force_download: true
    notary_force_reinstall: true
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

    version: 0.0.3

    # In this inventory, we're sharing the utility ip for the oracles and bitcoin node
    utility_ip: 159.203.159.124
    # The domain that will be used for the archive node published rpc
    archive_node_rpc_host: rpc.testnet.argonprotocol.org
    # We'll use our own rpc host, but we could have used any
    mainchain_rpc_url: "wss://{{ archive_node_rpc_host }}"
    # This is the notary id in the mainchain
    notary_id: 1
    # This is our notary domain registered in the mainchain
    notary_domain: notary1.testnet.argonprotocol.org
    nginx_letsencrypt_email: debug@argonprotocol.org

    bitcoin_proxy_rpc_port: 18332
    bitcoin_rpcauth: bitcoin:fcaf96fc56ef48bc0ef7979609bf72ee$2e66caabf3e287d2c404dead6da5931b7b89e52544a184bf39781c0c512f7a06
    bitcoin_rpc_url: "http://bitcoin:{{ vault_bitcoin_rpc_password }}@{{ utility_ip }}:{{ bitcoin_proxy_rpc_port }}" # testnet bitcoin rpc

    # These are dynamic vars, so don't do well if you put them into group_vars
    oracle_bitcoin_rpc_url: "{{ bitcoin_rpc_url }}"
    argon_node_bitcoin_rpc_url: "{{ bitcoin_rpc_url }}"

    notary_mainchain_rpc_url: "{{ mainchain_rpc_url }}"
    oracle_mainchain_rpc_url: "{{ mainchain_rpc_url }}"

    prometheus_rollup_nginx_password: "{{ vault_prometheus_nginx_password }}"
    oracle_bls_api_key: "{{ vault_oracle_bls_api_key }}"

  children:
    miners:
      children:
        archive_node:
          hosts:
            archive_node_1:
              ansible_host: 206.189.181.146
              argon_node_custom_options: [--alice] # use --author for a known author
              argon_node_p2p_private_key: "{{ vault_argon_node_p2p_private_key_archive_node }}"
              argon_node_p2p_public_addr_dns: bootnode0.testnet.argonprotocol.org
        workers:
          hosts:
            miner_node_1:
              ansible_host: 146.190.222.175
              argon_node_custom_options: [--bob]
              argon_node_p2p_private_key: "{{ vault_argon_node_p2p_private_key_miner_node_1 }}"
            miner_node_2:
              ansible_host: 174.138.36.46
              argon_node_custom_options: [--charlie]
              argon_node_p2p_private_key: "{{ vault_argon_node_p2p_private_key_miner_node_2 }}"
              argon_node_compute_miners: 1 # limit mining on this machine (it hosts other services)
    notary:
      hosts:
        notary_server:
          ansible_host: 137.184.58.22
    oracles:
      children:
        bitcoin_oracle:
          hosts:
            bitcoin_oracle_node:
              ansible_host: "{{ utility_ip }}"
        pricing_oracle:
          hosts:
            pricing_oracle_node:
              ansible_host: "{{ utility_ip }}"
    bitcoin:
      hosts:
        bitcoin_node:
          ansible_host: "{{ utility_ip }}"
