---
- name: Bitcoind | Ensure dependencies are installed
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - gpg
    - dirmngr
  # We only need to install these dependencies if we
  # have the GPG keys to verify the SHA256SUMS file
  when: bitcoin_pgp_builders_pub_key is defined and bitcoin_pgp_builders_pub_key | length > 0

- name: HAProxy | Install HAProxy
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
    - certbot

- name: Create bitcoin user
  ansible.builtin.import_role:
    name: user
  vars:
    user_name: "{{ bitcoin_user_name }}"

- name: HAProxy | Create renewal script
  ansible.builtin.template:
    src: reload-haproxy.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-haproxy.sh
    mode: "0755"
  when: bitcoin_electrs_domain != ""

- name: HAProxy | Create certs dir
  ansible.builtin.file:
    path: /etc/haproxy/certs
    state: directory
    mode: "0755"
    owner: root
    group: root


- name: HAProxy | Create ssl certs
  ansible.builtin.command:
    cmd: certbot certonly --webroot -w /var/www/letsencrypt -d {{ bitcoin_electrs_domain }} --non-interactive --agree-tos --email {{ bitcoin_certbot_email }}
  args:
    creates: /etc/letsencrypt/live/{{ bitcoin_electrs_domain }}/fullchain.pem
  when: bitcoin_electrs_domain != ""

- name: HAProxy | Auto renew ssl certs
  ansible.builtin.cron:
    name: "Certbot renew"
    job: "certbot renew --non-interactive --quiet"
    state: present
    minute: "0"
    hour: "0"
  when: bitcoin_electrs_domain != ""

- name: HAProxy | Copy HAProxy config
  ansible.builtin.template:
    src: bitcoin-rpc.haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  register: _haproxy_bitcoin_rpc

- name: Bitcoind role
  ansible.builtin.include_tasks: bitcoind.yml

- name: Activate Mining
  ansible.builtin.include_tasks: signet.yml
  when: bitcoin_signet_challenge != ""

- name: Electrs role
  ansible.builtin.include_tasks: electrs.yml
  when: bitcoin_electrs_enabled

- name: Restart HAProxy service # noqa: no-handler
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    daemon_reload: true
    enabled: true
  when: _haproxy_bitcoin_rpc.changed
